// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZd1gcapHDVlLQZxKEiUAG3DKU0WVzNrk',
    appId: '1:872147047659:web:204acc89dc9563fe641aae',
    messagingSenderId: '872147047659',
    projectId: 'test-2e1ad',
    authDomain: 'test-2e1ad.firebaseapp.com',
    storageBucket: 'test-2e1ad.firebasestorage.app',
    measurementId: 'G-CPL60CKWF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW8HCZgrNZ23eEv8gM8-7Le40lyHmWePA',
    appId: '1:872147047659:android:e1a80613f72462d3641aae',
    messagingSenderId: '872147047659',
    projectId: 'test-2e1ad',
    storageBucket: 'test-2e1ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Ty-_quTmLFpOI6waaIr86vzgvKo_LbU',
    appId: '1:872147047659:ios:36ab1e1fecf1da59641aae',
    messagingSenderId: '872147047659',
    projectId: 'test-2e1ad',
    storageBucket: 'test-2e1ad.firebasestorage.app',
    androidClientId: '872147047659-l36a4eveqt31crs8jm2584er9gb4cs42.apps.googleusercontent.com',
    iosClientId: '872147047659-d4unjnlk3o1jm9shm153ak52vgissqio.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Ty-_quTmLFpOI6waaIr86vzgvKo_LbU',
    appId: '1:872147047659:ios:36ab1e1fecf1da59641aae',
    messagingSenderId: '872147047659',
    projectId: 'test-2e1ad',
    storageBucket: 'test-2e1ad.firebasestorage.app',
    androidClientId: '872147047659-l36a4eveqt31crs8jm2584er9gb4cs42.apps.googleusercontent.com',
    iosClientId: '872147047659-d4unjnlk3o1jm9shm153ak52vgissqio.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZd1gcapHDVlLQZxKEiUAG3DKU0WVzNrk',
    appId: '1:872147047659:web:9062693a58bab751641aae',
    messagingSenderId: '872147047659',
    projectId: 'test-2e1ad',
    authDomain: 'test-2e1ad.firebaseapp.com',
    storageBucket: 'test-2e1ad.firebasestorage.app',
    measurementId: 'G-J5CHFWRB01',
  );
}
